services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Http\:
    resource: '%kernel.project_dir%/src/Infrastructure/Http/**/*Controller.php'
    tags: [ 'controller.service_arguments' ]
