imports:
  - { resource: 'http.yaml' }
  - { resource: 'cli.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Application\Factory\ProducerFactory\NotifyProducerFactory: ~

  App\Application\Service\ValidationService: ~

  App\Application\Service\Factory\ValidationFactory: ~

  App\Application\Service\ValidationCriteria\:
    resource: '%kernel.project_dir%/src/Application/Service/ValidationCriteria/*ValidationCriteria.php'