stages:
  - preparation
  - testing

variables:
  SSH_COMMAND: $SSH_COMMAND
  SMTP_CREDENTIALS: $SMTP_CREDENTIALS

composer:
  stage: preparation
  tags:
    - microservice
  script:
    - php -v
    - ls -la
    - make env
    - make restart
    - make composer-install

tests:
  stage: testing
  tags:
    - microservice
  dependencies:
    - composer
  script:
    - make test
    - make test-clean-output
    - make rm-cache
