stages:
  - manual-clean
  - preparation
  - testing

variables:
  SSH_COMMAND: $SSH_COMMAND
  SMTP_CREDENTIALS: $SMTP_CREDENTIALS

composer:
  stage: preparation
  tags:
    - microservice
  script:
    - php -v
    - ls -la
    - make env
    - docker-compose -f docker-compose.ci.yaml down
    - docker-compose -f docker-compose.ci.yaml up -d
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - make env
  artifacts:
    paths:
      - vendor/
      - docker-compose.yaml
    expire_in: 1 week
    when: always
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
      - docker-compose.yaml

tests:
  stage: testing
  tags:
    - microservice
  dependencies:
    - composer
  script:
    - make test
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm php vendor/codeception/codeception/codecept clean
    - make rm-cache

clean:
  stage: manual-clean
  script:
    - docker-compose -f docker-compose.ci.yaml up -d
    - docker-compose -f docker-compose.ci.yaml exec -T php-fpm rm -r var/log var/cache vendor/
  when: manual
