stages:
  - preparation
  - testing

variables:
  SSH_COMMAND: $SSH_COMMAND
  SMTP_CREDENTIALS: $SMTP_CREDENTIALS

composer:
  stage: preparation
  tags:
    - microservice
  script:
    - php -v
    - ls -la
    - make env
    - make restart
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - make env
  artifacts:
    paths:
      - vendor/
      - docker-compose.yaml
    expire_in: 1 month
    when: always
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
      - docker-compose.yaml

tests:
  stage: testing
  tags:
    - microservice
  dependencies:
    - composer
  script:
    - make test
    - make test-clean-output
    - make rm-cache
