services:
  _defaults:
    autowire: true
    autoconfigure: true

  consumers.email:
    class: App\Infrastructure\RabbitMq\Consumer\Email\EmailConsumer
    arguments:
      $logger: "@monolog.logger.receive_from_email"