services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\RabbitMq\Producer\Email\EmailProducer: '@old_sound_rabbit_mq.email_producer'

  App\Infrastructure\RabbitMq\Producer\History\HistoryMessageProducer: '@old_sound_rabbit_mq.history_producer'

  App\Infrastructure\RabbitMq\Producer\Telegram\TelegramProducer: '@old_sound_rabbit_mq.telegram_producer'

  App\Infrastructure\RabbitMq\Producer\Vkontakte\VkontakteProducer: '@old_sound_rabbit_mq.vkontakte_producer'

  App\Infrastructure\RabbitMq\Producer\Sms\SmsProducer: '@old_sound_rabbit_mq.sms_producer'