imports:
  - { resource: 'doctrine/repositories.yaml' }
  - { resource: 'doctrine/transactions.yaml' }
  - { resource: 'rabbitMq/consumer.yaml' }
  - { resource: 'rabbitMq/producer.yaml' }
  - { resource: 'sender/sender.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Doctrine\Service\NotifyMessageService: ~

  App\Infrastructure\Doctrine\Service\HistoryNotificationService: ~

  App\Infrastructure\Sender\Telegram\Service\TelegramSenderService:
    arguments:
      $apiToken: '%env(TELEGRAM_BOT_TOKEN)%'
      $logger: "@monolog.logger.telegram_service"

  App\Infrastructure\Sender\Vkontakte\Service\VkontakteSenderService:
    arguments:
      $accessToken: '%env(VK_ACCES_KEY)%'
      $groupId: '%env(VK_GROUP_ID)%'
      $peerId: '%env(VK_PEER_ID)%'

  App\Infrastructure\Sender\Sms\Service\SmsProviderResolver:
    arguments:
      $provider: '%env(SMS_PROVIDER)%'

  App\Infrastructure\Sender\Sms\Provider\:
    resource: '%kernel.project_dir%/src/Infrastructure/Sender/Sms/Provider/*Provider.php'

  App\Infrastructure\Sender\Discord\Service\DiscordSenderService:
    arguments:
      $webhookUri: '%env(DISCORD_WEBHOOK)%'
