imports:
  - { resource: 'doctrine/repositories.yaml' }
  - { resource: 'doctrine/transactions.yaml' }
  - { resource: 'rabbitMq/consumer.yaml' }
  - { resource: 'sender/sender.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Doctrine\Service\NotifyMessageService: ~

  App\Infrastructure\Doctrine\Service\HistoryNotificationService: ~