services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Sender\Email\EmailSender:
    arguments:
      $logger: "@monolog.logger.receive_notify"
      $emailSubject: '%env(EMAIL_SUBJECT)%'
      $emailFrom: '%env(EMAIL_FROM)%'

  App\Infrastructure\Sender\Telegram\TelegramSender:
    arguments:
      $logger: "@monolog.logger.receive_notify"